[project]
name = "bladeapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.2",
    "motor>=3.7.1",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.35.0",
]
